### ISSUE TITLE
Add support for Workload Identity Federation credentials

### ISSUE THREAD

**Issue by gpoulin-hopper** [GoogleCloudPlatform/gsutil#1407]
We want to be able to use gsutil from Github action using Workload Identity Federation to avoid creating Service Account key. However it seems like gsutil is limited in the type of credentials it can use.

https://github.com/google-github-actions/auth/issues/49

**Comment by marcus-kempe** [comment]
Is there any usable workaround for this?

**Comment by thomasmaclean** [comment]
There are no plans to add this to `gsutil`. You can use `gcloud alpha storage` as a workaround, for now. A non-preview version of the tool (`gcloud storage`) will be generally available in the first half of this year.

**Comment by leoschweizer** [comment]
> There are no plans to add this to `gsutil`. You can use `gcloud alpha storage` as a workaround, for now. A non-preview version of the tool (`gcloud storage`) will be generally available in the first half of this year.

`gcloud storage` is not nearly a replacement for `gsutil` though, e.g. you can't possibly do an `rsync` which is exactly what we would want to use `gsutil` for - with WIF.

**Comment by marcus-kempe** [comment]
>There are no plans to add this to gsutil. You can use gcloud alpha storage as a workaround, for now. A non-preview version of the tool (gcloud storage) will be generally available in the first half of this year.

Is the long-term plan to obsolete gsutil (and bq), and replace then with gcloud storage / gcloud bq instead, do you know?

**Comment by jvani** [comment]
@thomasmaclean, similar to @leoschweizer I want to use `gsutil rsync` with WIF. Are there any workarounds or suggestions?

**Comment by LoicSikidi** [comment]
Hi,

It seems that in the release [**379.0.0**](https://cloud.google.com/sdk/docs/release-notes#37900_2022-03-29) of gcloud,  the command below update `gsutil` creds file:

```bash
gcloud auth login --cred-file=external-account-creds.json
```

Check the code implementation [here](https://github.com/twistedpair/google-cloud-sdk/blob/master/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py#L1328-L1335).

**Comment by piotrekkr** [comment]
I can confirm that `gsutil` works now with OIDC:
```
jobs:
  dump:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    env:
      DUMP_BUCKET_PATH: 'gs://XXXXXX-sql-dump-staging/staging-database.sql.gz'
    steps:
      - name: Authorize in GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "${{ secrets.GCP_IDENTITY_POOL_PROVIDER_ID_STAGING }}"
          service_account: "${{ secrets.GCP_CI_SERVICE_ACCOUNT_EMAIL_STAGING }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Remove old dump
        run: |
          if gsutil ls "$DUMP_BUCKET_PATH" ; then
            gsutil rm -f -a "$DUMP_BUCKET_PATH"
          fi

```
`gsutil` generates this:
```
gs://XXXXXX-sql-dump-staging/staging-database.sql
Removing gs://XXXXXX-sql-dump-staging/staging-database.sql#1651578754808523...
/ [1 objects]                                                                   
Operation completed over 1 objects.
```

**Comment by alexUXUI** [comment]
Would be great if we could merge in the docs update. I was bitten by this and this docs update would have saved me. Thanks!

**Comment by andreas-hakansson-ingka** [comment]
We're having some issues getting this to work. We're doing similar to what @piotrekkr shared, but when we call `gsutil` we get the following error

> ('Error code invalid_request: Invalid value for "audience". This value should be the full resource name of the Identity Provider. See https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token for the list of possible formats.', '{"error":"invalid_request","error_description":"Invalid value for \\"audience\\". This value should be the full resource name of the Identity Provider. See https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token for the list of possible formats."}')

We're using Workload Identity Federation for other steps, such as deploying to Cloud Run, and it works just fine. I've checked our Workload Identity Federation setup and we have mapped `attribute.aud` to `assertion.aud` so that value should be set correctly from the GitHub token

```yaml
-   name: Acquire Google Cloud Platform token
    id: auth
    uses: google-github-actions/auth@v0
    with:
        create_credentials_file: true
        workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com

-   name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v0
```

The secrets have all been set (and we know they're working since we're using WIF for other things). The `gsutil` command that we're running from inside a script (actually a Makefile) is

```shell
gsutil -m cp -r gs://<bucketname>/<foldername> <localpath>/
```

Not suer why we're getting an issue with `audience` only for `gsutil` commands.

**Comment by andreas-hakansson-ingka** [comment]
@thomasmaclean any thoughts on the above?

**Comment by piotrekkr** [comment]
@andreas-hakansson-ingka Just my guess but maybe you have some kind of typo in `workflow_identity_provider` value? I'm using value I get from terraform `google_iam_workload_identity_pool_provider.github.name` and it works for me.

**Comment by andreas-hakansson-ingka** [comment]
@piotrekkr hmm the same `workflow_identity_provider` value work with other GCP actions like `google-github-actions/deploy-cloudrun`. I'll try and verify that they're correct

**Comment by piotrekkr** [comment]
@andreas-hakansson-ingka Another thing you could try is using different version of `gsutil` by using `google-github-actions/setup-gcloud@v1` or more specific versions.

**Comment by shermanericts** [comment]
Hey there.  Sorry to bump this thread.
Workload identity works great for most of the gsutil commands I've tried, `i.e. gsutil cp` is fine.

However, when I try to use the `gsutil signurl` command, it fails.  I can only use the `credentials_json` option:

-----

dispatch .yaml
```
steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 'auth service account'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Generate Signed URL
        uses: ./actions/generate-signed-url
```

Inside the action, this gets invoked:
```
gsutil signurl -d 10m $GOOGLE_GHA_CREDS_PATH gs://XXX/blah.txt
```

I expected: the signed url

I receive:

```
/opt/hostedtoolcache/gcloud/412.0.0/x64/platform/bundledpythonunix/lib/python3.9/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Keystore password:Traceback (most recent call last):
  File "/opt/hostedtoolcache/gcloud/412.0.0/x64/platform/gsutil/gslib/commands/signurl.py", line 543, in RunCommand
    key, client_email = _ReadJSONKeystore(
  File "/opt/hostedtoolcache/gcloud/412.0.0/x64/platform/gsutil/gslib/commands/signurl.py", line 360, in _ReadJSONKeystore
    raise ValueError('JSON keystore doesn\'t contain required fields')
ValueError: JSON keystore doesn't contain required fields

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/gcloud/412.0.0/x64/platform/bundledpythonunix/lib/python3.9/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Inappropriate ioctl for device')
```

Again, same service account works fine using credentials_json.  gsutil cp works fine with workload identity.
