### ISSUE TITLE
gsutil + docker + GOOGLE_APPLICATION_CREDENTIALS help

### ISSUE THREAD

**Issue by cjmcgraw** [GoogleCloudPlatform/gsutil#1463]
Hey guys. I commented before on #447 about this. Decided to open this as a separate issue. I'll describe my problem in as much detail with as much direct code as possible to alleviate confusion about what I am trying to do.

For this project I am working in docker containers solely. I want to be able to communicate with gsutil when running containers on my local machine, but also run them in my CI/CD environment, and production using the same container with minimal configuration.

I want to work under the following assumption. The user has the following environmental variables defined, conditional on environment:
```bash
# locally
export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/.config/gcloud/application_default_credentials.json

# ci/cd, production
export GOOGLE_APPLICATION_CREDENTIALS=/some-service-account.json
```

Here is an example of a docker-compose.yml
```yaml
version: 3.9

services:
   gsutil_test_container:
     build: .
     volumes:
       - $GOOGLE_APPLICATION_CREDENTIALS:/creds
     environment:
       GOOGLE_APPLICATION_CREDENTIALS: "/creds" 
```

Here is my dockerfile:
```Dockerfile
FROM google/cloud-sdk
COPY docker-entrypoint.sh .
ENTRYPOINT [ "./docker-entrypoint.sh" ]
```

Here is my docker-entrypoint.sh:
```bash
#! /usr/bin/env bash
gsutil ls
```

What I want to do: `docker-compose run gsutil_test_container`
